// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\ADC_J_minus.s
// Created: 2025-03-06 18:12:06
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


import Subsystem_pkg::* ;

// -------------------------------------------------------------
// 
// Module: ADC_J_minus
// Source Path: Simulink_SPGD_simulation_HDL_code_generator_v5_5/Subsystem/SPGD Subsystem/ADC_J_minus
// Hierarchy Level: 2
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module ADC_J_minus
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic  dco,             
             input logic  [15:0] data,           
             input logic Enable,
             output logic [15:0] DO_rsvd
    );

  logic busy;
  logic enb_gated;
  logic adc_data_valid;
  logic sys_clk;
  logic [15:0] AI;
  logic [17:0] AI_extended;
  logic [15:0] AI_bypass;  /* ufix16_En6 */
  logic [15:0] AI_last_value;  /* ufix16_En6 */
  
  assign enb_gated = Enable && enb;
 
ltc2207_capture_module adc2(
    .adc_clkout(dco),  // ADC clock
    .sample_in(enb_gated),   // External async sample trigger
    .reset_in(reset),    // External async reset
    .din(data),        // ADC data input
    .dout(AI),        // Latched data output
    .busy(busy)         // High while sampling in progress
);
  
  //assign AI = AI_extended[17:2];
  always_ff @(posedge clk or posedge reset)
    begin : DO_bypass_process
      if (reset == 1'b1) begin
        AI_last_value <= 16'b0000000000000000;
      end
      else begin
        if (enb_gated) begin
          AI_last_value <= AI_bypass;
        end
      end
    end



  assign AI_bypass = (Enable == 1'b0 ? AI_last_value :
              AI);


  assign DO_rsvd = AI_bypass;

endmodule  // ADC_J_minus

