// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\DAC1.s
// Created: 2025-03-06 18:12:06
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


import Subsystem_pkg::* ;

// -------------------------------------------------------------
// 
// Module: DAC1
// Source Path: Simulink_SPGD_simulation_HDL_code_generator_v5_5/Subsystem/SPGD Subsystem/DAC1
// Hierarchy Level: 2
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module DAC1
          (  input logic clk,
             input logic reset,
             input logic enb,
             input vector_of_signed_logic_16 DI[0:7]  /* sfix16_En13 [8] */,
             input logic Enable,
             output vector_of_signed_logic_12 DAC_out [0:7],
             output [7:0] wr);



  logic enb_gated;
  assign enb_gated = Enable && enb;
  vector_of_signed_logic_12 output_holder [0:7];
  logic [7:0] wr_holder;
  logic dac_valid;
  logic busy;
 
 genvar index0;
    generate
      for(index0 = 32'sd0; index0 <= 32'sd7; index0 = index0 + 32'sd1) begin: DAC_block_gen
        ltc1666_parallel_interface DAC_block (.clk(clk),
                                             .reset(reset),       
                                             .start(enb_gated),       
                                             .dac_data(DI[index0]),    
                                             .dac_out(output_holder[index0]),     
                                             .wr(wr_holder[index0]),          
                                             .dac_valid(dac_valid),   
                                             .busy(busy));   
      end
    endgenerate 
   
   
  assign DAC_out = output_holder;
  assign wr = wr_holder;

endmodule  // DAC1

