// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\dither_gen_FixPt.s
// Created: 2025-03-06 18:12:06
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


import Subsystem_pkg::* ;

// -------------------------------------------------------------
// 
// Module: dither_gen_FixPt
// Source Path: Simulink_SPGD_simulation_HDL_code_generator_v5_5/Subsystem/Generate dither/dither_gen/dither_gen_FixPt
// Hierarchy Level: 3
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dither_gen_FixPt
          #(  parameter vector_of_signed_logic_2 a0 [0:63] = '{1, 1, 1, 1, 1, 1, 1, 1, 
                                                               1, -1, 1, -1, 1, -1, 1, -1, 
                                                               1, 1, -1, -1, 1, 1, -1, -1, 
                                                               1, -1, -1, 1, 1, -1, -1, 1,
                                                               1, 1, 1, 1, -1, -1, -1, -1, 
                                                               1, -1, 1, -1, -1, 1, -1, 1, 
                                                               1, 1, -1, -1, -1, -1, 1, 1, 
                                                               1, -1, -1, 1, -1, 1, 1, -1})
          (  input logic [15:0] orms  /* ufix16_En16 */,
             input logic [15:0] u  /* ufix16_En14 */,
             output vector_of_signed_logic_16 y[0:7] [0:7]  /* sfix16_En16 [8x8] */,
             output logic [15:0] enable  /* ufix16_En14 */);


  vector_of_signed_logic_16 c7_y [0:63];  /* sfix16_En16 [64] */
  logic [15:0] enable_1;  /* ufix16_En14 */
  logic signed [31:0] t_0;  /* int32 */
  vector_of_signed_logic_17 cast [0:63];  /* sfix17_En16 [64] */
  vector_of_signed_logic_19 mul_temp [0:63];  /* sfix19_En16 [64] */
  vector_of_signed_logic_18 cast_0 [0:63];  /* sfix18_En16 [64] */
  vector_of_signed_logic_17 cast_1 [0:63];  /* sfix17_En16 [64] */
  vector_of_signed_logic_35 mul_temp_0 [0:63];  /* sfix35_En32 [64] */
  vector_of_signed_logic_34 cast_2 [0:63];  /* sfix34_En32 [64] */


  always @(orms, u) begin
    //auto-generated
    if (u == 16'b0100000000000000) begin
      for(t_0 = 32'sd0; t_0 <= 32'sd63; t_0 = t_0 + 32'sd1) begin
        cast[t_0] = {1'b0, orms};/* sfix17_En16 */
        mul_temp[t_0] = a0[t_0] * cast[t_0];/* sfix19_En16 */
        cast_0[t_0] = mul_temp[t_0][17:0];/* sfix18_En16 */
        cast_1[t_0] = {1'b0, orms};/* sfix17_En16 */
        mul_temp_0[t_0] = cast_0[t_0] * cast_1[t_0];/* sfix35_En32 */
        cast_2[t_0] = mul_temp_0[t_0][33:0];/* sfix34_En32 */
        c7_y[t_0] = cast_2[t_0][32:17];/* sfix16_En15 */
      end
    end
    else begin
      c7_y = '{64{16'sb0000000000000000}};
    end
    enable_1 = 16'b0100000000000000;
  end



  generate
    genvar idx1;
    for(idx1 = 0; idx1 < 8; idx1 = idx1 + 1) begin : y_gen1
      genvar idx;
      for(idx = 0; idx < 8; idx = idx + 1) begin : y_gen
        assign y[idx][idx1] = c7_y[idx + (idx1 * 8)];
      end
    end
  endgenerate

  assign enable = enable_1;
  
  /*                                                   '{1, 0, 0, 0, 0, 0, 0, 0, 
                                                         0, 1, 0, 0, 0, 0, 0, 0, 
                                                         0, 0, 1, 0, 0, 0, 0, 0, 
                                                         0, 0, 0, 1, 0, 0, 0, 0,
                                                         0, 0, 0, 0, 1, 0, 0, 0, 
                                                         0, 0, 0, 0, 0, 1, 0, 0, 
                                                         0, 0, 0, 0, 0, 0, 1, 0, 
                                                         0, 0, 0, 0, 0, 0, 0, 1})    Identity
             
                                                             '{1, 1, 1, 1, 1, 1, 1, 1, 
                                                               1, -1, 1, -1, 1, -1, 1, -1, 
                                                               1, 1, -1, -1, 1, 1, -1, -1, 
                                                               1, -1, -1, 1, 1, -1, -1, 1,
                                                               1, 1, 1, 1, -1, -1, -1, -1, 
                                                               1, -1, 1, -1, -1, 1, -1, 1, 
                                                               1, 1, -1, -1, -1, -1, 1, 1, 
                                                               1, -1, -1, 1, -1, 1, 1, -1}    Hadamard
                                                               
                                                               '{1, 1, 1, 1, 1, 1, 1, 1, 
                                                               1, -1, 1, -1, 1, -1, 1, -1, 
                                                               1, 1, -1, -1, 1, 1, -1, -1, 
                                                               1, -1, -1, 1, 1, -1, -1, 1, 
                                                               -1, -1, -1, -1, 1, 1, 1, 1, 
                                                               -1, 1, -1, 1, 1, -1, 1, -1, 
                                                               -1, -1, 1, 1, 1, 1, -1, -1, 
                                                               -1, 1, 1, -1, 1, -1, -1, 1}     Flipped Hadamard - x
                                                               
                                                               '{-1, -1, -1, -1, 1, 1, 1, 1, 
                                                               -1, 1, -1, 1, 1, -1, 1, -1, 
                                                               -1, -1, 1, 1, 1, 1, -1, -1, 
                                                               -1, 1, 1, -1, 1, -1, -1, 1,
                                                               -1, -1, -1, -1, -1, -1, -1, -1, 
                                                               -1, 1, -1, 1, -1, 1, -1, 1, 
                                                               -1, -1, 1, 1, -1, -1, 1, 1, 
                                                               -1, 1, 1, -1, -1, 1, 1, -1}     Flipped Hadamard - symmetric
                                                               
                                                               
                                                               */    

endmodule  // dither_gen_FixPt

