// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\dither_gen.s
// Created: 2025-03-06 18:12:06
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


import Subsystem_pkg::* ;

// -------------------------------------------------------------
// 
// Module: dither_gen
// Source Path: Simulink_SPGD_simulation_HDL_code_generator_v5_5/Subsystem/Generate dither/dither_gen
// Hierarchy Level: 2
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dither_gen
          (  input logic [15:0] orms  /* ufix16_En16 */,
             input logic [15:0] u  /* ufix16_En14 */,
             output vector_of_signed_logic_16 y[0:7] [0:7]  /* sfix16_En16 [8x8] */,
             output logic [15:0] enable  /* ufix16_En14 */);



  // This variant subsystem was automatically generated by the Fixed-Point Tool to convert a MATLAB function block to 
  // fixed-point.The variant subsystem contains two blocks:
  // 1. MATLAB Function is the original code from the MATLAB function block. Modify this block to update your code or 
  // resolve errors
  // 
  // 2. MATLAB Function_FixPt is the generated fixed-point code for the MATLAB function block. Any modifications to 
  // this block will be overwritten on the next conversion.
  // 
  // The Fixed-Point Tool will select an appropriate variant based on the Model Settings. Learn more. 


  dither_gen_FixPt u_dither_gen_FixPt (.orms(orms),  /* ufix16_En16 */
                                       .u(u),  /* ufix16_En14 */
                                       .y(y),  /* sfix16_En16 [8x8] */
                                       .enable(enable)  /* ufix16_En14 */
                                       );

endmodule  // dither_gen

