// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\Generate_dither.s
// Created: 2025-03-06 18:12:06
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


import Subsystem_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Generate_dither
// Source Path: Simulink_SPGD_simulation_HDL_code_generator_v5_5/Subsystem/Generate dither
// Hierarchy Level: 1
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Generate_dither
          (  input logic [15:0] orms  /* ufix16_En16 */,
             input logic [15:0] type_of_dither_to_load  /* ufix16_En14 */,
             output vector_of_signed_logic_16 dither_out[0:7] [0:7]  /* sfix16_En16 [8x8] */,
             output logic [15:0] dither_ready_enable  /* ufix16_En14 */);


  vector_of_signed_logic_16 dither_gen_out1 [0:7] [0:7];  /* sfix16_En16 [8x8] */
  logic [15:0] dither_gen_out2;  /* ufix16_En14 */


  dither_gen u_dither_gen (.orms(orms),  /* ufix16_En16 */
                           .u(type_of_dither_to_load),  /* ufix16_En14 */
                           .y(dither_gen_out1),  /* sfix16_En16 [8x8] */
                           .enable(dither_gen_out2)  /* ufix16_En14 */
                           );

  assign dither_out = dither_gen_out1;

  assign dither_ready_enable = dither_gen_out2;

endmodule  // Generate_dither

