// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\perturb_dither_minus.s
// Created: 2025-03-06 18:12:06
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


import Subsystem_pkg::* ;

// -------------------------------------------------------------
// 
// Module: perturb_dither_minus
// Source Path: Simulink_SPGD_simulation_HDL_code_generator_v5_5/Subsystem/SPGD Subsystem/perturb_dither_minus
// Hierarchy Level: 2
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module perturb_dither_minus
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic [15:0] V2pi,
             input vector_of_signed_logic_16 dither_in[0:7]  /* sfix16_En16 [8] */,
             input vector_of_signed_logic_16 phase_shiter_vector[0:7]  /* sfix16_En11 [8] */,
             input logic Enable,
             output vector_of_signed_logic_16 dither_out[0:7]  /* sfix16_En13 [8] */,
             output vector_of_signed_logic_16 subtract_out_copy[0:7]);


  logic enb_gated;
  vector_of_signed_logic_32 Subtract_sub_cast [0:7];  /* sfix32_En16 [8] */
  vector_of_signed_logic_32 Subtract_sub_cast_1 [0:7];  /* sfix32_En16 [8] */
  vector_of_signed_logic_32 Subtract_sub_temp [0:7];  /* sfix32_En16 [8] */
  vector_of_signed_logic_16 Subtract_out1 [0:7];  /* sfix16_En13 [8] */
  vector_of_signed_logic_16 Subtract_out1_bypass [0:7];  /* sfix16_En13 [8] */
  vector_of_signed_logic_16 Subtract_out1_last_value [0:7];  /* sfix16_En13 [8] */
  vector_of_signed_logic_16 V2pi_wrap_vector [0:7];
  logic signed [15:0] V2pi_casted;
  logic signed [15:0] DAC_max_voltage;
  assign enb_gated = Enable && enb;
  assign V2pi_casted = {1'b0, V2pi[14:0]};/*sfix16_12frac*/
  assign DAC_max_voltage = 16'sb0100000000000000;/*sfix16_12frac - 4 Volt v2 DAC*/


  genvar t_01;
  generate
    for(t_01 = 32'sd0; t_01 <= 32'sd7; t_01 = t_01 + 32'sd1) begin:Subtract_out1_gen
      assign Subtract_sub_cast[t_01] = {{12{phase_shiter_vector[t_01][15]}}, {phase_shiter_vector[t_01], 4'b0000}};
      assign Subtract_sub_cast_1[t_01] = {{16{dither_in[t_01][15]}}, dither_in[t_01]};
      assign Subtract_sub_temp[t_01] = Subtract_sub_cast[t_01] - Subtract_sub_cast_1[t_01];
      assign Subtract_out1[t_01] = Subtract_sub_temp[t_01][18:3];
    end
  endgenerate


genvar t_02;
  generate
    for(t_02 = 32'sd0; t_02 <= 32'sd7; t_02 = t_02 + 32'sd1) begin:V2pi_wrap_minus
      always_ff @(posedge clk)
      begin
      if (reset == 1'b1) begin
        V2pi_wrap_vector[t_02] <= 16'sb0000000000000000;
      end
      else begin
          if (Subtract_out1[t_02] > DAC_max_voltage) begin
             V2pi_wrap_vector[t_02] <= Subtract_out1[t_02] - V2pi_casted;
          end
          else if (Subtract_out1[t_02] < 0) begin
             V2pi_wrap_vector[t_02] <= Subtract_out1[t_02] + V2pi_casted;
          end
          else begin
             V2pi_wrap_vector[t_02] <= Subtract_out1[t_02];
          end
      end
      end
    end
  endgenerate

  always_ff @(posedge clk or posedge reset)
    begin : dither_out_bypass_process
      if (reset == 1'b1) begin
        Subtract_out1_last_value <= '{8{16'sb0000000000000000}};
      end
      else begin
        if (enb_gated) begin
          Subtract_out1_last_value <= Subtract_out1_bypass;
        end
      end
    end



  assign Subtract_out1_bypass = (Enable == 1'b0 ? Subtract_out1_last_value :
              V2pi_wrap_vector);



  assign dither_out = Subtract_out1_bypass;/*sfix16_12frac*/
  assign subtract_out_copy = Subtract_out1;

endmodule  // perturb_dither_minus

