// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\select_vector.s
// Created: 2025-03-06 18:12:06
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


import Subsystem_pkg::* ;

// -------------------------------------------------------------
// 
// Module: select_vector
// Source Path: Simulink_SPGD_simulation_HDL_code_generator_v5_5/Subsystem/SPGD Subsystem/select_vector
// Hierarchy Level: 2
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module select_vector
          (  input logic clk,
             input logic reset,
             input logic [3:0] epoch_bit_select,
             input logic [15:0] epoch,
             input vector_of_signed_logic_16 matrix_in[0:7] [0:7]  /* sfix16_En16 [8x8] */,
             input logic [15:0] index  /* ufix16_En11 */,
             output vector_of_signed_logic_16 vector_out[0:7]  /* sfix16_En16 [8] */);



  // This variant subsystem was automatically generated by the Fixed-Point Tool to convert a MATLAB function block to 
  // fixed-point.The variant subsystem contains two blocks:
  // 1. MATLAB Function1 is the original code from the MATLAB function block. Modify this block to update your code 
  // or resolve errors
  // 
  // 2. MATLAB Function1_FixPt is the generated fixed-point code for the MATLAB function block. Any modifications to 
  // this block will be overwritten on the next conversion.
  // 
  // The Fixed-Point Tool will select an appropriate variant based on the Model Settings. Learn more. 


  select_vector_FixPt u_select_vector_FixPt (.clk(clk),
                                             .reset(reset),
                                             .epoch_bit_select(epoch_bit_select),
                                             .epoch(epoch),
                                             .matrix_in(matrix_in),  /* sfix16_En16 [8x8] */
                                             .index(index),  /* ufix16_En11 */
                                             .vector_out(vector_out)  /* sfix16_En16 [8] */
                                             );

endmodule  // select_vector

