// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\select_vector_FixPt.s
// Created: 2025-03-06 18:12:06
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


import Subsystem_pkg::* ;

// -------------------------------------------------------------
// 
// Module: select_vector_FixPt
// Source Path: Simulink_SPGD_simulation_HDL_code_generator_v5_5/Subsystem/SPGD Subsystem/select_vector/select_vector_FixPt
// Hierarchy Level: 3
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module select_vector_FixPt
          (  input logic clk,
             input logic reset,
             input logic [3:0] epoch_bit_select,
             input logic [15:0] epoch,
             input vector_of_signed_logic_16 matrix_in[0:7] [0:7]  /* sfix16_En16 [8x8] */,
             input logic [15:0] index  /* ufix16_En11 */,
             output vector_of_signed_logic_16 vector_out[0:7]  /* sfix16_En16 [8] */);


  vector_of_signed_logic_32 sub_cast [0:7];  /* int32 [8] */
  
  genvar t_01;
  generate
    for(t_01 = 32'sd0; t_01 <= 32'sd7; t_01 = t_01 + 32'sd1) begin:vector_out_gen
      assign sub_cast[t_01] = {27'b0, index[15:11]};
      always_comb begin
          if (epoch[epoch_bit_select] == 1'b0)
              vector_out[t_01] = matrix_in[t_01][sub_cast[t_01] - 32'd1];
          else
              vector_out[t_01] = ~matrix_in[t_01][sub_cast[t_01] - 32'd1] + 16'b1;
      end
      //assign vector_out[t_01] = matrix_in[t_01][sub_cast[t_01] - 32'd1];
    end
  endgenerate




endmodule  // select_vector_FixPt

