// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\state_machine.s
// Created: 2025-03-06 18:12:06
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


import Subsystem_pkg::* ;

// -------------------------------------------------------------
// 
// Module: state_machine
// Source Path: Simulink_SPGD_simulation_HDL_code_generator_v5_5/Subsystem/SPGD Subsystem/state_machine
// Hierarchy Level: 2
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module state_machine
          (  input logic clk,
		     input logic [15:0] counter_in  /* ufix16_En12 */,
             input logic [2:0] cur_state  /* ufix16_En11 */,
             input logic [2:0] projected_state_in  /* ufix16_En11 */,
             input vector_of_unsigned_logic_16 wait_time_batch[0:7]  /* ufix16_En12 [8] */,
             input vector_of_unsigned_logic_16 hold_time_batch[0:7]  /* ufix16_En14 [8] */,
             output logic [15:0] counter_out  /* ufix16_En12 */,
             output logic DAC_enable_out,
             output logic J_plus_ADC_enable_out,
             output logic J_minus_ADC_enable_out,
             output logic plus_perturb_enable_out,
             output logic minus_perturb_enable_out,
             output logic SPGD_update_enable_out,
             output logic [2:0] next_state  /* ufix16_En11 */,
             output logic [2:0] projected_state  /* ufix16_En11 */,
             output logic [15:0] plus_minus_select  /* ufix16_En14 */);



  // This variant subsystem was automatically generated by the Fixed-Point Tool to convert a MATLAB function block to 
  // fixed-point.The variant subsystem contains two blocks:
  // 1. MATLAB Function is the original code from the MATLAB function block. Modify this block to update your code or 
  // resolve errors
  // 
  // 2. MATLAB Function_FixPt is the generated fixed-point code for the MATLAB function block. Any modifications to 
  // this block will be overwritten on the next conversion.
  // 
  // The Fixed-Point Tool will select an appropriate variant based on the Model Settings. Learn more. 


  state_machine_FixPt u_state_machine_FixPt (.clk(clk),
                                             .counter_in(counter_in),  /* ufix16_En12 */
                                             .cur_state(cur_state),  /* ufix16_En11 */
                                             .projected_state_in(projected_state_in),  /* ufix16_En11 */
                                             .wait_time_batch(wait_time_batch),  /* ufix16_En12 [8] */
                                             .hold_time_batch(hold_time_batch),  /* ufix16_En14 [8] */
                                             .counter_out(counter_out),  /* ufix16_En12 */
                                             .DAC_enable_out(DAC_enable_out),
                                             .J_plus_ADC_enable_out(J_plus_ADC_enable_out),
                                             .J_minus_ADC_enable_out(J_minus_ADC_enable_out),
                                             .plus_perturb_enable_out(plus_perturb_enable_out),
                                             .minus_perturb_enable_out(minus_perturb_enable_out),
                                             .SPGD_update_enable_out(SPGD_update_enable_out),
                                             .next_state(next_state),  /* ufix16_En11 */
                                             .projected_state(projected_state),  /* ufix16_En11 */
                                             .plus_minus_select(plus_minus_select)  /* ufix16_En14 */
                                             );

endmodule  // state_machine

