// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\Subsystem.s
// Created: 2025-03-06 18:12:06
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.02
// Target subsystem base rate: 0.02
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.02
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// out_monitor                   ce_out        0.02
// ADC1_enable_out               ce_out        0.02
// DAC_enable_out                ce_out        0.02
// state_out                     ce_out        0.02
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------




// -------------------------------------------------------------
// 
// Module: Subsystem
// Source Path: Simulink_SPGD_simulation_HDL_code_generator_v5_5/Subsystem
// Hierarchy Level: 0
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem
          (  input logic clk,
             input logic [15:0] DAC_in,
             input logic reset,
             input logic clk_enable,
             input logic [15:0] PM_index,
             input logic [15:0] system_check_enable  /* ufix16_En15 */,
             input logic [15:0] type_of_dither_to_load  /* ufix16_En14 */,
             input logic [15:0] g  /* ufix16_En12 */,
             input logic [15:0] g_leakage  /* ufix16_En15 */,
             input logic [15:0] orms  /* ufix16_En16 */,
             input logic [15:0] beta1  /* ufix16_En16 */,
             input logic [15:0] max_iterations  /* ufix16_En5 */,
             input logic [15:0] V2pi  /* ufix16_En12 */,
             output logic ce_out,
             output logic [15:0] out_monitor  /* ufix16_En11 */,
             input  logic      dco,             
             input  logic [15:0]         data,    
             input logic [3:0] epoch_bit_select,       
             output vector_of_signed_logic_12 DAC_out [0:7],
             output logic [15:0] updated_dither_monitor1,
             output [7:0] wr,
             output logic cnv,
             output logic cnv2,
             output [2:0] state_out,
             output DAC_enable_out,
             output ADC1_enable_out,
             output logic [15:0] data_captured,
             output logic [15:0] PM0,
             output logic [15:0] PMP0,
             output logic [15:0] PMM0,
             output logic [15:0] dither0,
             output logic [15:0] delta_S      );

  logic enb;
  vector_of_signed_logic_16 y [0:7] [0:7];  /* sfix16_En16 [8x8] */
  logic [15:0] enable;  /* ufix16_En14 */
  logic [15:0] Constant_out1;  /* ufix16_En15 */
  logic [14:0] Memory_out1;  /* ufix16_En2 */
  logic [15:0] sign_extended_memory_out1;
  logic [31:0] Add_add_cast;  /* ufix32_En15 */
  logic [31:0] Add_add_cast_1;  /* ufix32_En15 */
  logic [31:0] Add_add_temp;  /* ufix32_En15 */
  logic [15:0] Add_out1;  /* ufix16_En2 */
  vector_of_unsigned_logic_16 Constant7_out1 [0:7];  /* ufix16_En12 [8] */
  vector_of_unsigned_logic_16 Constant1_out1 [0:7];  /* ufix16_En14 [8] */
  logic enable_is_not0;
  logic system_check_enable_is_not0;
  logic Relational_Operator_relop1;
  logic Logical_Operator_out1;
  logic [15:0] SPGD_Subsystem_out1;  /* ufix16_En6 */
  logic SPGD_Subsystem_out2;
  logic SPGD_Subsystem_out3;
  logic [2:0] SPGD_Subsystem_out4;  /* ufix16_En11 */
  logic [15:0] SPGD_Subsystem_out15;
  logic [15:0] SPGD_Subsystem_out25;
  logic [15:0] SPGD_Subsystem_out35;


  Generate_dither u_Generate_dither (.orms(orms),  /* ufix16_En16 */
                                     .type_of_dither_to_load(type_of_dither_to_load),  /* ufix16_En14 */
                                     .dither_out(y),  /* sfix16_En16 [8x8] */
                                     .dither_ready_enable(enable)  /* ufix16_En14 */
                                     );

  assign Constant_out1 = 16'b0000000000000001;



  assign enb = clk_enable;
  logic counter_enb;
  assign counter_enb = enb && Relational_Operator_relop1;

  always_ff @(posedge clk or posedge reset)
    begin : Memory_process
      if (reset == 1'b1) begin
        Memory_out1 <= 16'b0000000000000100;
      end
      else begin
        if (counter_enb) begin
          Memory_out1 <= Memory_out1 + Constant_out1;
        end
        else begin
          Memory_out1 <= Memory_out1;
        end
      end
    end



  // parameter sequence state 7, 1, 2, 3 ... 6, 0: number of clk cycles in total for a state sequence and for the state control to hold high respectively (the difference gives idle state 0 time)
  
  assign Constant7_out1[0] = 16'b0000000000001111;
  assign Constant7_out1[1] = 16'b0000000000001111;
  assign Constant7_out1[2] = 16'b0000110010000000;
  assign Constant7_out1[3] = 16'b0000110010000000;
  assign Constant7_out1[4] = 16'b0000000000001111;
  assign Constant7_out1[5] = 16'b0000110010000000;
  assign Constant7_out1[6] = 16'b0000110010000000;
  assign Constant7_out1[7] = 16'b0000000000000001;
  /*
  assign Constant7_out1[0] = 16'b0000000000001111;
  assign Constant7_out1[1] = 16'b0000000000000011;
  assign Constant7_out1[2] = 16'b0000000000110010;
  assign Constant7_out1[3] = 16'b0000000000110010;
  assign Constant7_out1[4] = 16'b0000000000000011;
  assign Constant7_out1[5] = 16'b0000000000110010;
  assign Constant7_out1[6] = 16'b0000000000110010;
  assign Constant7_out1[7] = 16'b0000000000000001;
*/


  assign Constant1_out1[0] = 16'b0000000000000111;
  assign Constant1_out1[1] = 16'b0000000000001110;
  assign Constant1_out1[2] = 16'b0000000000000001;
  assign Constant1_out1[3] = 16'b0000000011001000;
  assign Constant1_out1[4] = 16'b0000000000001110;
  assign Constant1_out1[5] = 16'b0000000000000001;
  assign Constant1_out1[6] = 16'b0000000011001000;
  assign Constant1_out1[7] = 16'b0000000000000001;




  assign enable_is_not0 = enable != 16'b0000000000000000;



  assign system_check_enable_is_not0 = system_check_enable != 16'b0000000000000000;


  assign sign_extended_memory_out1 = {1'b0, Memory_out1};
  assign Relational_Operator_relop1 = sign_extended_memory_out1 <= max_iterations;



  assign Logical_Operator_out1 = Relational_Operator_relop1 & (enable_is_not0 & system_check_enable_is_not0);



  
  SPGD_Subsystem u_SPGD_Subsystem (.clk(clk),
                                   .reset(reset),
                                   .DAC_in(DAC_in),
                                   .enb(clk_enable),
                                   .PM_index(PM_index),
                                   .g(g),  /* ufix16_En12 */
                                   .g_leakage(g_leakage),  /* ufix16_En15 */
                                   .measured_signal(measured_signal),
                                   .orms(orms),  /* ufix16_En16 */
                                   .beta1(beta1),
                                   .dither_in(y),  /* sfix16_En16 [8x8] */
                                   .pseudo_clk(Memory_out1),  /* ufix16_En5 */
                                   .wait_times(Constant7_out1),  /* ufix16_En12 [8] */
                                   .hold_times(Constant1_out1),  /* ufix16_En13 [8] */
                                   .V2pi(V2pi),  /* ufix16_En12 */
                                   .Enable(Logical_Operator_out1),
                                   .epoch_bit_select(epoch_bit_select),
                                   .out_monitor(SPGD_Subsystem_out1),  /* ufix16_En11 */
                                   .DAC_enable_out(SPGD_Subsystem_out2),
                                   .ADC1_enable_out(SPGD_Subsystem_out3),
                                   .state_out(SPGD_Subsystem_out4),  /* ufix16_En11 */
								   .counter_feedback(SPGD_Subsystem_out15),
								   .updated_dither_monitor1(updated_dither_monitor1),
								   .updated_dither_monitor2(SPGD_Subsystem_out35),
								   .dco(dco),             
                                   .data(data),           
                                   .DAC_out(DAC_out),
                                   .wr(wr),
                                   .cnv_adc(cnv),
                                   .cnv_adc2(cnv2),
                                   .data_captured(data_captured),
                                   .PM0(PM0),
                                   .PMP0(PMP0),
                                   .PMM0(PMM0),
                                   .dither0(dither0),
                                   .delta_S(delta_S)
                                   );

  assign out_monitor = SPGD_Subsystem_out1;

  assign ADC1_enable_out = SPGD_Subsystem_out3;

  assign DAC_enable_out = SPGD_Subsystem_out2;

  assign state_out = SPGD_Subsystem_out4;

  //assign ce_out = clk_enable;
  
  //assign dither_selection_index_out = SPGD_Subsystem_out15;
  
  //assign updated_dither_monitor_out1 = SPGD_Subsystem_out25;
  
  //assign updated_dither_monitor_out2 = SPGD_Subsystem_out35;
  
endmodule  // Subsystem

