// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\Subsystem_pkg.s
// Created: 2025-03-06 18:12:06
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------



package Subsystem_pkg;
  typedef  logic signed [15:0] vector_of_signed_logic_16;
  typedef  logic signed [1:0] vector_of_signed_logic_2;
  typedef  logic signed [16:0] vector_of_signed_logic_17;
  typedef  logic signed [11:0] vector_of_signed_logic_12;
  typedef  logic signed [18:0] vector_of_signed_logic_19;
  typedef  logic signed [17:0] vector_of_signed_logic_18;
  typedef  logic signed [34:0] vector_of_signed_logic_35;
  typedef  logic signed [33:0] vector_of_signed_logic_34;

  typedef  logic signed [31:0] vector_of_signed_logic_32;
  typedef  logic signed [32:0] vector_of_signed_logic_33;

  typedef  logic  [15:0] vector_of_unsigned_logic_16;

  typedef  logic signed [49:0] vector_of_signed_logic_50;
  typedef  logic signed [69:0] vector_of_signed_logic_70;
  typedef  logic signed [51:0] vector_of_signed_logic_52;
  typedef  logic signed [68:0] vector_of_signed_logic_69;
  typedef  logic  [31:0] vector_of_unsigned_logic_32;
  typedef  logic  [47:0] vector_of_unsigned_logic_48;
  typedef  logic signed [50:0] vector_of_signed_logic_51;
  typedef  logic signed [47:0] vector_of_signed_logic_48;
endpackage: Subsystem_pkg

