// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\Subsystem_tb.s
// Created: 2025-03-06 18:12:22
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.02
// Target subsystem base rate: 0.02
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_tb
// Source Path: 
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_tb;

  logic clk;
  logic reset;
  logic clk_enable;
  logic [15:0] rawData_system_check_enable;  /* ufix16_En15 */
  logic [15:0] rawData_type_of_dither_to_load;  /* ufix16_En14 */
  logic [15:0] rawData_g;  /* ufix16_En15 */
  logic [15:0] rawData_g_leakage;  /* ufix16_En15 */
  logic [15:0] rawData_orms;  /* ufix16_En16 */
  logic [15:0] rawData_max_iterations;  /* ufix16_En2 */
  logic [15:0] rawData_V2pi;  /* ufix16_En12 */
  logic state_out_done;  /* ufix1 */
  logic rdEnb;
  logic state_out_done_enb;  /* ufix1 */
  logic [12:0] out_monitor_addr;  /* ufix13 */
  logic state_out_lastAddr;  /* ufix1 */
  logic resetn;
  logic check4_done;  /* ufix1 */
  logic DAC_enable_out_done;  /* ufix1 */
  logic DAC_enable_out_done_enb;  /* ufix1 */
  logic DAC_enable_out_lastAddr;  /* ufix1 */
  logic check3_done;  /* ufix1 */
  logic ADC1_enable_out_done;  /* ufix1 */
  logic ADC1_enable_out_done_enb;  /* ufix1 */
  logic ADC1_enable_out_lastAddr;  /* ufix1 */
  logic check2_done;  /* ufix1 */
  logic out_monitor_done;  /* ufix1 */
  logic out_monitor_done_enb;  /* ufix1 */
  logic out_monitor_active;  /* ufix1 */
  logic [15:0] holdData_V2pi;  /* ufix16_En12 */
  logic [15:0] V2pi_offset;  /* ufix16_En12 */
  logic [15:0] V2pi_1;  /* ufix16_En12 */
  logic [15:0] holdData_max_iterations;  /* ufix16_En2 */
  logic [15:0] max_iterations_offset;  /* ufix16_En2 */
  logic [15:0] max_iterations_1;  /* ufix16_En2 */
  logic [15:0] holdData_orms;  /* ufix16_En16 */
  logic [15:0] orms_offset;  /* ufix16_En16 */
  logic [15:0] orms_1;  /* ufix16_En16 */
  logic [15:0] holdData_g_leakage;  /* ufix16_En15 */
  logic [15:0] g_leakage_offset;  /* ufix16_En15 */
  logic [15:0] g_leakage_1;  /* ufix16_En15 */
  logic [15:0] holdData_g;  /* ufix16_En15 */
  logic [15:0] g_offset;  /* ufix16_En15 */
  logic [15:0] g_1;  /* ufix16_En15 */
  logic [15:0] holdData_type_of_dither_to_load;  /* ufix16_En14 */
  logic [15:0] type_of_dither_to_load_offset;  /* ufix16_En14 */
  logic [15:0] type_of_dither_to_load_1;  /* ufix16_En14 */
  logic [15:0] holdData_system_check_enable;  /* ufix16_En15 */
  logic [15:0] system_check_enable_offset;  /* ufix16_En15 */
  logic [15:0] system_check_enable_1;  /* ufix16_En15 */
  logic snkDone;
  logic snkDonen;
  logic tb_enb;
  logic tb_enb_delay;
  logic ce_out;
  logic [15:0] out_monitor;  /* ufix16_En6 */
  logic ADC1_enable_out;
  logic DAC_enable_out;
  logic [15:0] state_out;  /* ufix16_En11 */
  logic out_monitor_enb;  /* ufix1 */
  logic out_monitor_lastAddr;  /* ufix1 */
  logic check1_done;  /* ufix1 */
  logic [12:0] out_monitor_addr_delay_1;  /* ufix13 */
  logic signed [31:0] fp_out_monitor_expected;  /* sfix32 */
  logic [15:0] out_monitor_expected;  /* ufix16_En6 */
  logic signed [31:0] status_out_monitor_expected;  /* sfix32 */
  logic [15:0] out_monitor_ref;  /* ufix16_En6 */
  logic out_monitor_testFailure;  /* ufix1 */
  logic [12:0] ADC1_enable_out_addr_delay_1;  /* ufix13 */
  logic signed [31:0] fp_ADC1_enable_out_expected;  /* sfix32 */
  logic ADC1_enable_out_expected;
  logic signed [31:0] status_ADC1_enable_out_expected;  /* sfix32 */
  logic ADC1_enable_out_ref;
  logic ADC1_enable_out_testFailure;  /* ufix1 */
  logic [12:0] DAC_enable_out_addr_delay_1;  /* ufix13 */
  logic signed [31:0] fp_DAC_enable_out_expected;  /* sfix32 */
  logic DAC_enable_out_expected;
  logic signed [31:0] status_DAC_enable_out_expected;  /* sfix32 */
  logic DAC_enable_out_ref;
  logic DAC_enable_out_testFailure;  /* ufix1 */
  logic [12:0] state_out_addr_delay_1;  /* ufix13 */
  logic signed [31:0] fp_state_out_expected;  /* sfix32 */
  logic [15:0] state_out_expected;  /* ufix16_En11 */
  logic signed [31:0] status_state_out_expected;  /* sfix32 */
  logic [15:0] state_out_ref;  /* ufix16_En11 */
  logic state_out_testFailure;  /* ufix1 */
  logic testFailure;  /* ufix1 */


  // Data source for system_check_enable
  assign rawData_system_check_enable = 16'b1000000000000000;



  // Data source for type_of_dither_to_load
  assign rawData_type_of_dither_to_load = 16'b0100000000000000;



  // Data source for g
  assign rawData_g = 16'b1000000000000000;



  // Data source for g_leakage
  assign rawData_g_leakage = 16'b1000000000000000;



  // Data source for orms
  assign rawData_orms = 16'b0100110011001101;



  // Data source for max_iterations
  assign rawData_max_iterations = 16'b1110101001100000;



  // Data source for V2pi
  assign rawData_V2pi = 16'b0011101100110011;



  assign state_out_done_enb = state_out_done & rdEnb;



  assign state_out_lastAddr = out_monitor_addr >= 13'b1001110001000;



  assign state_out_done = state_out_lastAddr & resetn;



  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_4
      if (reset) begin
        check4_done <= 0;
      end
      else begin
        if (state_out_done_enb) begin
          check4_done <= state_out_done;
        end
      end
    end

  assign DAC_enable_out_done_enb = DAC_enable_out_done & rdEnb;



  assign DAC_enable_out_lastAddr = out_monitor_addr >= 13'b1001110001000;



  assign DAC_enable_out_done = DAC_enable_out_lastAddr & resetn;



  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_3
      if (reset) begin
        check3_done <= 0;
      end
      else begin
        if (DAC_enable_out_done_enb) begin
          check3_done <= DAC_enable_out_done;
        end
      end
    end

  assign ADC1_enable_out_done_enb = ADC1_enable_out_done & rdEnb;



  assign ADC1_enable_out_lastAddr = out_monitor_addr >= 13'b1001110001000;



  assign ADC1_enable_out_done = ADC1_enable_out_lastAddr & resetn;



  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_2
      if (reset) begin
        check2_done <= 0;
      end
      else begin
        if (ADC1_enable_out_done_enb) begin
          check2_done <= ADC1_enable_out_done;
        end
      end
    end

  assign out_monitor_done_enb = out_monitor_done & rdEnb;



  assign out_monitor_active = out_monitor_addr != 13'b1001110001000;



  // holdData reg for Constant7_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Constant7_out1
      if (reset) begin
        holdData_V2pi <= 16'bx;
      end
      else begin
        holdData_V2pi <= rawData_V2pi;
      end
    end

  always @(rawData_V2pi or rdEnb)
    begin : stimuli_Constant7_out1_1
      if (rdEnb == 1'b0) begin
        V2pi_offset <= holdData_V2pi;
      end
      else begin
        V2pi_offset <= rawData_V2pi;
      end
    end

  assign #2 V2pi_1 = V2pi_offset;

  // holdData reg for Constant6_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Constant6_out1
      if (reset) begin
        holdData_max_iterations <= 16'bx;
      end
      else begin
        holdData_max_iterations <= rawData_max_iterations;
      end
    end

  always @(rawData_max_iterations or rdEnb)
    begin : stimuli_Constant6_out1_1
      if (rdEnb == 1'b0) begin
        max_iterations_offset <= holdData_max_iterations;
      end
      else begin
        max_iterations_offset <= rawData_max_iterations;
      end
    end

  assign #2 max_iterations_1 = max_iterations_offset;

  // holdData reg for Constant4_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Constant4_out1
      if (reset) begin
        holdData_orms <= 16'bx;
      end
      else begin
        holdData_orms <= rawData_orms;
      end
    end

  always @(rawData_orms or rdEnb)
    begin : stimuli_Constant4_out1_1
      if (rdEnb == 1'b0) begin
        orms_offset <= holdData_orms;
      end
      else begin
        orms_offset <= rawData_orms;
      end
    end

  assign #2 orms_1 = orms_offset;

  // holdData reg for Constant3_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Constant3_out1
      if (reset) begin
        holdData_g_leakage <= 16'bx;
      end
      else begin
        holdData_g_leakage <= rawData_g_leakage;
      end
    end

  always @(rawData_g_leakage or rdEnb)
    begin : stimuli_Constant3_out1_1
      if (rdEnb == 1'b0) begin
        g_leakage_offset <= holdData_g_leakage;
      end
      else begin
        g_leakage_offset <= rawData_g_leakage;
      end
    end

  assign #2 g_leakage_1 = g_leakage_offset;

  // holdData reg for Constant2_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Constant2_out1
      if (reset) begin
        holdData_g <= 16'bx;
      end
      else begin
        holdData_g <= rawData_g;
      end
    end

  always @(rawData_g or rdEnb)
    begin : stimuli_Constant2_out1_1
      if (rdEnb == 1'b0) begin
        g_offset <= holdData_g;
      end
      else begin
        g_offset <= rawData_g;
      end
    end

  assign #2 g_1 = g_offset;

  // holdData reg for Constant1_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Constant1_out1
      if (reset) begin
        holdData_type_of_dither_to_load <= 16'bx;
      end
      else begin
        holdData_type_of_dither_to_load <= rawData_type_of_dither_to_load;
      end
    end

  always @(rawData_type_of_dither_to_load or rdEnb)
    begin : stimuli_Constant1_out1_1
      if (rdEnb == 1'b0) begin
        type_of_dither_to_load_offset <= holdData_type_of_dither_to_load;
      end
      else begin
        type_of_dither_to_load_offset <= rawData_type_of_dither_to_load;
      end
    end

  assign #2 type_of_dither_to_load_1 = type_of_dither_to_load_offset;

  // holdData reg for Constant_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Constant_out1
      if (reset) begin
        holdData_system_check_enable <= 16'bx;
      end
      else begin
        holdData_system_check_enable <= rawData_system_check_enable;
      end
    end

  always @(rawData_system_check_enable or rdEnb)
    begin : stimuli_Constant_out1_1
      if (rdEnb == 1'b0) begin
        system_check_enable_offset <= holdData_system_check_enable;
      end
      else begin
        system_check_enable_offset <= rawData_system_check_enable;
      end
    end

  assign #2 system_check_enable_1 = system_check_enable_offset;

  assign snkDonen =  ~ snkDone;



  assign resetn =  ~ reset;



  assign tb_enb = resetn & snkDonen;



  // Delay inside enable generation: register depth 1
  always @(posedge clk or posedge reset)
    begin : u_enable_delay
      if (reset) begin
        tb_enb_delay <= 0;
      end
      else begin
        tb_enb_delay <= tb_enb;
      end
    end

  assign rdEnb = (snkDone == 1'b0 ? tb_enb_delay :
              1'b0);



  assign #2 clk_enable = rdEnb;

  initial
    begin : reset_gen
      reset <= 1'b1;
      # (20);
      @ (posedge clk)
      # (2);
      reset <= 1'b0;
    end

  always 
    begin : clk_gen
      clk <= 1'b1;
      # (5);
      clk <= 1'b0;
      # (5);
      if (snkDone == 1'b1) begin
        clk <= 1'b1;
        # (5);
        clk <= 1'b0;
        # (5);
        $stop;
      end
    end

  Subsystem u_Subsystem (.clk(clk),
                         .reset(reset),
                         .clk_enable(clk_enable),
                         .system_check_enable(system_check_enable_1),  /* ufix16_En15 */
                         .type_of_dither_to_load(type_of_dither_to_load_1),  /* ufix16_En14 */
                         .g(g_1),  /* ufix16_En15 */
                         .g_leakage(g_leakage_1),  /* ufix16_En15 */
                         .orms(orms_1),  /* ufix16_En16 */
                         .max_iterations(max_iterations_1),  /* ufix16_En2 */
                         .V2pi(V2pi_1),  /* ufix16_En12 */
                         .ce_out(ce_out),
                         .out_monitor(out_monitor),  /* ufix16_En6 */
                         .ADC1_enable_out(ADC1_enable_out),
                         .DAC_enable_out(DAC_enable_out),
                         .state_out(state_out)  /* ufix16_En11 */
                         );

  assign out_monitor_enb = ce_out & out_monitor_active;



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 5000
  always_ff @(posedge clk or posedge reset)
    begin : c_2_process
      if (reset == 1'b1) begin
        out_monitor_addr <= 13'b0000000000000;
      end
      else begin
        if (out_monitor_enb) begin
          if (out_monitor_addr >= 13'b1001110001000) begin
            out_monitor_addr <= 13'b0000000000000;
          end
          else begin
            out_monitor_addr <= out_monitor_addr + 13'b0000000000001;
          end
        end
      end
    end



  assign out_monitor_lastAddr = out_monitor_addr >= 13'b1001110001000;



  assign out_monitor_done = out_monitor_lastAddr & resetn;



  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_1
      if (reset) begin
        check1_done <= 0;
      end
      else begin
        if (out_monitor_done_enb) begin
          check1_done <= out_monitor_done;
        end
      end
    end

  assign snkDone = check4_done & (check3_done & (check1_done & check2_done));



  assign #1 out_monitor_addr_delay_1 = out_monitor_addr;

  // Data source for out_monitor_expected
  initial
    begin : out_monitor_expected_fileread
      fp_out_monitor_expected = $fopen("out_monitor_expected.dat", "r");
      status_out_monitor_expected = $rewind(fp_out_monitor_expected);
    end

  always @(out_monitor_addr_delay_1, ce_out, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        out_monitor_expected <= 16'bx;
      end
      else if (ce_out == 1) begin
        status_out_monitor_expected = $fscanf(fp_out_monitor_expected, "%h", out_monitor_expected);
      end
    end

  assign out_monitor_ref = out_monitor_expected;

  always @(posedge clk or posedge reset)
    begin : out_monitor_checker
      if (reset == 1'b1) begin
        out_monitor_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && out_monitor !== out_monitor_ref) begin
          out_monitor_testFailure <= 1'b1;
          $display("ERROR in out_monitor at time %t : Expected '%h' Actual '%h'", $time, out_monitor_ref, out_monitor);
        end
      end
    end

  assign #1 ADC1_enable_out_addr_delay_1 = out_monitor_addr;

  // Data source for ADC1_enable_out_expected
  initial
    begin : ADC1_enable_out_expected_fileread
      fp_ADC1_enable_out_expected = $fopen("ADC1_enable_out_expected.dat", "r");
      status_ADC1_enable_out_expected = $rewind(fp_ADC1_enable_out_expected);
    end

  always @(ADC1_enable_out_addr_delay_1, ce_out, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        ADC1_enable_out_expected <= 1'bx;
      end
      else if (ce_out == 1) begin
        status_ADC1_enable_out_expected = $fscanf(fp_ADC1_enable_out_expected, "%h", ADC1_enable_out_expected);
      end
    end

  assign ADC1_enable_out_ref = ADC1_enable_out_expected;

  always @(posedge clk or posedge reset)
    begin : ADC1_enable_out_checker
      if (reset == 1'b1) begin
        ADC1_enable_out_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && ADC1_enable_out !== ADC1_enable_out_ref) begin
          ADC1_enable_out_testFailure <= 1'b1;
          $display("ERROR in ADC1_enable_out at time %t : Expected '%h' Actual '%h'", $time, ADC1_enable_out_ref, ADC1_enable_out);
        end
      end
    end

  assign #1 DAC_enable_out_addr_delay_1 = out_monitor_addr;

  // Data source for DAC_enable_out_expected
  initial
    begin : DAC_enable_out_expected_fileread
      fp_DAC_enable_out_expected = $fopen("DAC_enable_out_expected.dat", "r");
      status_DAC_enable_out_expected = $rewind(fp_DAC_enable_out_expected);
    end

  always @(DAC_enable_out_addr_delay_1, ce_out, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        DAC_enable_out_expected <= 1'bx;
      end
      else if (ce_out == 1) begin
        status_DAC_enable_out_expected = $fscanf(fp_DAC_enable_out_expected, "%h", DAC_enable_out_expected);
      end
    end

  assign DAC_enable_out_ref = DAC_enable_out_expected;

  always @(posedge clk or posedge reset)
    begin : DAC_enable_out_checker
      if (reset == 1'b1) begin
        DAC_enable_out_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && DAC_enable_out !== DAC_enable_out_ref) begin
          DAC_enable_out_testFailure <= 1'b1;
          $display("ERROR in DAC_enable_out at time %t : Expected '%h' Actual '%h'", $time, DAC_enable_out_ref, DAC_enable_out);
        end
      end
    end

  assign #1 state_out_addr_delay_1 = out_monitor_addr;

  // Data source for state_out_expected
  initial
    begin : state_out_expected_fileread
      fp_state_out_expected = $fopen("state_out_expected.dat", "r");
      status_state_out_expected = $rewind(fp_state_out_expected);
    end

  always @(state_out_addr_delay_1, ce_out, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        state_out_expected <= 16'bx;
      end
      else if (ce_out == 1) begin
        status_state_out_expected = $fscanf(fp_state_out_expected, "%h", state_out_expected);
      end
    end

  assign state_out_ref = state_out_expected;

  always @(posedge clk or posedge reset)
    begin : state_out_checker
      if (reset == 1'b1) begin
        state_out_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && state_out !== state_out_ref) begin
          state_out_testFailure <= 1'b1;
          $display("ERROR in state_out at time %t : Expected '%h' Actual '%h'", $time, state_out_ref, state_out);
        end
      end
    end

  assign testFailure = state_out_testFailure | (DAC_enable_out_testFailure | (out_monitor_testFailure | ADC1_enable_out_testFailure));



  always @(posedge clk)
    begin : completed_msg
      if (snkDone == 1'b1) begin
        if (testFailure == 1'b0) begin
          $display("**************TEST COMPLETED (PASSED)**************");
        end
        else begin
          $display("**************TEST COMPLETED (FAILED)**************");
        end
      end
    end

endmodule  // Subsystem_tb

