// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\vector_counter.s
// Created: 2025-03-06 18:12:06
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


import Subsystem_pkg::* ;

// -------------------------------------------------------------
// 
// Module: vector_counter
// Source Path: Simulink_SPGD_simulation_HDL_code_generator_v5_5/Subsystem/SPGD Subsystem/Update dither to phase 
// shifters/vector_counte
// Hierarchy Level: 3
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module vector_counter
          (  input logic [15:0] u  /* ufix16_En11 */,
             output logic [15:0] y  /* ufix16_En11 */);



  // This variant subsystem was automatically generated by the Fixed-Point Tool to convert a MATLAB function block to 
  // fixed-point.The variant subsystem contains two blocks:
  // 1. MATLAB Function is the original code from the MATLAB function block. Modify this block to update your code or 
  // resolve errors
  // 
  // 2. MATLAB Function_FixPt is the generated fixed-point code for the MATLAB function block. Any modifications to 
  // this block will be overwritten on the next conversion.
  // 
  // The Fixed-Point Tool will select an appropriate variant based on the Model Settings. Learn more. 


  vector_counter_FixPt u_vector_counter_FixPt (.u(u),  /* ufix16_En11 */
                                               .y(y)  /* ufix16_En11 */
                                               );

endmodule  // vector_counter

