// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\vector_counter_FixPt.s
// Created: 2025-03-06 18:12:06
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


import Subsystem_pkg::* ;

// -------------------------------------------------------------
// 
// Module: vector_counter_FixPt
// Source Path: Simulink_SPGD_simulation_HDL_code_generator_v5_5/Subsystem/SPGD Subsystem/Update dither to phase 
// shifters/vector_counter/vector_counter_FixP
// Hierarchy Level: 4
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module vector_counter_FixPt
          (  input logic [15:0] u  /* ufix16_En11 */,
             output logic [15:0] y  /* ufix16_En11 */);




  //auto-generated
  assign y = (u < 16'b0100000000000000 ? u + 16'b0000100000000000 :
              16'b0000100000000000);



endmodule  // vector_counter_FixPt

