// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\vector_handle_FixPt.s
// Created: 2025-03-06 18:12:06
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


import Subsystem_pkg::* ;

// -------------------------------------------------------------
// 
// Module: vector_handle_FixPt
// Source Path: Simulink_SPGD_simulation_HDL_code_generator_v5_5/Subsystem/SPGD Subsystem/vector_handle/vector_handle_FixPt
// Hierarchy Level: 3
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module vector_handle_FixPt
          (  input logic clk,
             input logic reset_1,
             input logic [15:0] V2pi  /* ufix16_En12 */,
             input vector_of_signed_logic_16 v_in[0:7]  /* sfix16_En11 [8] */,
             output vector_of_signed_logic_16 v_out[0:7]  /* sfix16_En11 [8] */);


  vector_of_signed_logic_16 v_out_1 [0:7];  /* sfix16_En11 [8] */
  logic signed [15:0] V2pi_casted;
  logic signed [15:0] DAC_max_voltage;
  assign V2pi_casted = {1'b0, V2pi[15:1]};
  assign DAC_max_voltage = 16'sb0001111111111111;/*sfix16_11frac - 4 Volt v2 DAC*/
  
  genvar i;
  generate
    for(i = 32'sd0; i <= 32'sd7; i = i + 32'sd1) begin
      always_ff @ (posedge clk or posedge reset_1) begin
        if (reset_1) begin
            v_out_1[i] <= 16'sb0000000000000000;
        end
        else begin
             //if negative
            if (v_in[i] < 0) begin
              v_out_1[i] <= v_in[i] + V2pi_casted;/* sfix16_En11 [8] */
            end
            //if > V2pi
            else if (v_in[i] > DAC_max_voltage) begin
              v_out_1[i] <= v_in[i] - V2pi_casted;/* sfix16_En11 [8] */
            end
             //if valid
            else begin
              v_out_1[i] <= v_in[i];/* sfix16_En11 [8] */
            end
         end
      end
    end
  endgenerate
  assign v_out = v_out_1;

endmodule  // vector_handle_FixPt

