// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\vector_handle.s
// Created: 2025-03-06 18:12:06
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


import Subsystem_pkg::* ;

// -------------------------------------------------------------
// 
// Module: vector_handle
// Source Path: Simulink_SPGD_simulation_HDL_code_generator_v5_5/Subsystem/SPGD Subsystem/vector_handle
// Hierarchy Level: 2
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module vector_handle
          (  input clk,
             input logic reset_1,
             input logic [15:0] V2pi  /* ufix16_En12 */,
             input vector_of_signed_logic_16 v_in[0:7]  /* sfix16_En13 [8] */,
             output vector_of_signed_logic_16 v_out[0:7]  /* sfix16_En11 [8] */);



  // This variant subsystem was automatically generated by the Fixed-Point Tool to convert a MATLAB function block to 
  // fixed-point.The variant subsystem contains two blocks:
  // 1. MATLAB Function3 is the original code from the MATLAB function block. Modify this block to update your code 
  // or resolve errors
  // 
  // 2. MATLAB Function3_FixPt is the generated fixed-point code for the MATLAB function block. Any modifications to 
  // this block will be overwritten on the next conversion.
  // 
  // The Fixed-Point Tool will select an appropriate variant based on the Model Settings. Learn more. 


  vector_handle_FixPt u_vector_handle_FixPt (.clk(clk),
                                             .reset_1(reset_1),
                                             .V2pi(V2pi),  /* ufix16_En12 */
                                             .v_in(v_in),  /* sfix16_En13 [8] */
                                             .v_out(v_out)  /* sfix16_En11 [8] */
                                             );

endmodule  // vector_handle

