// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\wave_propagation_FixPt.s
// Created: 2025-03-06 18:12:06
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


import Subsystem_pkg::* ;

// -------------------------------------------------------------
// 
// Module: wave_propagation_FixPt
// Source Path: Simulink_SPGD_simulation_HDL_code_generator_v5_5/Subsystem/SPGD Subsystem/wave_propagation/wave_propagation_FixPt
// Hierarchy Level: 3
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module wave_propagation_FixPt
          #(  parameter vector_of_unsigned_logic_16 nc [0:7] = '{4096, 1638, 4096, 8192, 12288, 19660, 819, 1638}  /* ufix16 [8] */)
          (  input vector_of_signed_logic_16 in[0:7]  /* sfix16_En13 [8] */,
             output logic [15:0] out  /* ufix16_En6 */);


  logic [15:0] out_1;  /* ufix16_En6 */
  logic [15:0] beams_combined_real;  /* ufix16_En11 */
  logic signed [15:0] beams_combined_imag;  /* sfix16_En9 */
  logic [31:0] y;  /* ufix32_En22 */
  logic signed [31:0] y_0;  /* sfix32_En18 */
  logic signed [50:0] a;  /* sfix51_En40 */
  logic signed [50:0] c;  /* sfix51_En40 */
  logic signed [31:0] i;  /* int32 */
  vector_of_signed_logic_18 add_cast [0:7];  /* sfix18_En13 [8] */
  vector_of_signed_logic_18 add_cast_0 [0:7];  /* sfix18_En13 [8] */
  vector_of_signed_logic_18 add_temp [0:7];  /* sfix18_En13 [8] */
  vector_of_signed_logic_17 cast [0:7];  /* sfix17_En13 [8] */
  vector_of_signed_logic_33 mul_temp [0:7];  /* sfix33_En26 [8] */
  vector_of_signed_logic_32 cast_0 [0:7];  /* sfix32_En26 [8] */
  vector_of_signed_logic_50 mul_temp_0 [0:7];  /* sfix50_En39 [8] */
  logic signed [37:0] add_cast_1;  /* sfix38_En22 */
  logic signed [37:0] add_cast_2;  /* sfix38_En22 */
  logic signed [37:0] add_temp_0;  /* sfix38_En22 */
  vector_of_signed_logic_70 add_cast_3 [0:7];  /* sfix70_En54 [8] */
  vector_of_signed_logic_52 sub_cast [0:7];  /* sfix52_En40 [8] */
  vector_of_signed_logic_52 sub_temp [0:7];  /* sfix52_En40 [8] */
  vector_of_signed_logic_70 add_cast_4 [0:7];  /* sfix70_En54 [8] */
  vector_of_signed_logic_70 add_temp_1 [0:7];  /* sfix70_En54 [8] */
  vector_of_signed_logic_69 add_cast_5 [0:7];  /* sfix69_En53 [8] */
  vector_of_signed_logic_50 sub_cast_0 [0:7];  /* sfix50_En39 [8] */
  vector_of_unsigned_logic_32 mul_temp_1 [0:7];  /* ufix32_En26 [8] */
  vector_of_unsigned_logic_48 mul_temp_2 [0:7];  /* ufix48_En39 [8] */
  vector_of_signed_logic_50 sub_cast_1 [0:7];  /* sfix50_En39 [8] */
  vector_of_signed_logic_50 sub_temp_0 [0:7];  /* sfix50_En39 [8] */
  vector_of_signed_logic_51 add_cast_6 [0:7];  /* sfix51_En39 [8] */
  vector_of_signed_logic_51 add_cast_7 [0:7];  /* sfix51_En39 [8] */
  vector_of_signed_logic_51 add_temp_2 [0:7];  /* sfix51_En39 [8] */
  vector_of_signed_logic_52 sub_cast_2 [0:7];  /* sfix52_En39 [8] */
  vector_of_signed_logic_32 mul_temp_3 [0:7];  /* sfix32_En26 [8] */
  vector_of_signed_logic_48 mul_temp_4 [0:7];  /* sfix48_En39 [8] */
  vector_of_signed_logic_52 sub_cast_3 [0:7];  /* sfix52_En39 [8] */
  vector_of_signed_logic_52 sub_temp_1 [0:7];  /* sfix52_En39 [8] */
  vector_of_signed_logic_69 add_cast_8 [0:7];  /* sfix69_En53 [8] */
  vector_of_signed_logic_69 add_temp_3 [0:7];  /* sfix69_En53 [8] */


  always_comb begin
    c = 51'sh0000000000000;
    a = 51'sh0000000000000;
    //auto-generated
    beams_combined_real = 16'b0000000000000000;
    beams_combined_imag = 16'sb0000000000000000;

    for(i = 32'sd0; i <= 32'sd7; i = i + 32'sd1) begin
      add_cast[i] = {2'b0, nc[i]};
      add_cast_0[i] = {{2{in[i][15]}}, in[i]};
      add_temp[i] = add_cast[i] + add_cast_0[i];
      cast[i] = {1'b0, nc[i]};
      mul_temp[i] = cast[i] * in[i];
      cast_0[i] = mul_temp[i][31:0];
      mul_temp_0[i] = add_temp[i] * cast_0[i];
      a = {mul_temp_0[i], 1'b0};
      c = a >>> 8'd1;
      add_cast_3[i] = {11'b0, {beams_combined_real, 43'b0000000000000000000000000000000000000000000}};
      sub_cast[i] = {c[50], c};
      sub_temp[i] = 52'sh0010000000000 - sub_cast[i];
      add_cast_4[i] = {{4{sub_temp[i][51]}}, {sub_temp[i], 14'b00000000000000}};
      add_temp_1[i] = add_cast_3[i] + add_cast_4[i];
      beams_combined_real = add_temp_1[i][58:43];
      add_cast_5[i] = {{9{beams_combined_imag[15]}}, {beams_combined_imag, 44'b00000000000000000000000000000000000000000000}};
      sub_cast_0[i] = {8'b0, {nc[i], 26'b00000000000000000000000000}};
      mul_temp_1[i] = nc[i] * nc[i];
      mul_temp_2[i] = mul_temp_1[i] * nc[i];
      sub_cast_1[i] = {2'b0, mul_temp_2[i]};
      sub_temp_0[i] = sub_cast_0[i] - sub_cast_1[i];
      add_cast_6[i] = {sub_temp_0[i][49], sub_temp_0[i]};
      add_cast_7[i] = {{9{in[i][15]}}, {in[i], 26'b00000000000000000000000000}};
      add_temp_2[i] = add_cast_6[i] + add_cast_7[i];
      sub_cast_2[i] = {add_temp_2[i][50], add_temp_2[i]};
      mul_temp_3[i] = in[i] * in[i];
      mul_temp_4[i] = mul_temp_3[i] * in[i];
      sub_cast_3[i] = {{4{mul_temp_4[i][47]}}, mul_temp_4[i]};
      sub_temp_1[i] = sub_cast_2[i] - sub_cast_3[i];
      add_cast_8[i] = {{3{sub_temp_1[i][51]}}, {sub_temp_1[i], 14'b00000000000000}};
      add_temp_3[i] = add_cast_5[i] + add_cast_8[i];
      beams_combined_imag = add_temp_3[i][59:44];
    end

    y = beams_combined_real * beams_combined_real;
    y_0 = beams_combined_imag * beams_combined_imag;
    add_cast_1 = {6'b0, y};
    add_cast_2 = {{2{y_0[31]}}, {y_0, 4'b0000}};
    add_temp_0 = add_cast_1 + add_cast_2;
    out_1 = add_temp_0[31:16];
  end



  assign out = out_1;

endmodule  // wave_propagation_FixPt

