// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\wave_propagation.s
// Created: 2025-03-06 18:12:06
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


import Subsystem_pkg::* ;

// -------------------------------------------------------------
// 
// Module: wave_propagation
// Source Path: Simulink_SPGD_simulation_HDL_code_generator_v5_5/Subsystem/SPGD Subsystem/wave_propagation
// Hierarchy Level: 2
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module wave_propagation
          (  input vector_of_signed_logic_16 in[0:7]  /* sfix16_En13 [8] */,
             output logic [15:0] out  /* ufix16_En6 */);



  // This variant subsystem was automatically generated by the Fixed-Point Tool to convert a MATLAB function block to 
  // fixed-point.The variant subsystem contains two blocks:
  // 1. wave_propagation is the original code from the MATLAB function block. Modify this block to update your code 
  // or resolve errors
  // 
  // 2. wave_propagation_FixPt is the generated fixed-point code for the MATLAB function block. Any modifications to 
  // this block will be overwritten on the next conversion.
  // 
  // The Fixed-Point Tool will select an appropriate variant based on the Model Settings. Learn more. 


  wave_propagation_FixPt u_wave_propagation_FixPt (.in(in),  /* sfix16_En13 [8] */
                                                   .out(out)  /* ufix16_En6 */
                                                   );

endmodule  // wave_propagation

