// -------------------------------------------------------------
// 
// File Name: C:\Users\Laser Phased Array\Desktop\SimuLink Simulations\Systemverilog code from HDL coder\v5 - globally 
// generalized state machine\Simulink_SPGD_simulation_HDL_code_generator_v5_5\zero_handle.s
// Created: 2025-03-06 18:12:06
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


import Subsystem_pkg::* ;

// -------------------------------------------------------------
// 
// Module: zero_handle
// Source Path: Simulink_SPGD_simulation_HDL_code_generator_v5_5/Subsystem/SPGD Subsystem/zero_handle
// Hierarchy Level: 2
// Model version: 1.49
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module zero_handle
          (  input logic [15:0] u  /* ufix16_En11 */,
             output logic [15:0] y  /* ufix16_En11 */);



  // This variant subsystem was automatically generated by the Fixed-Point Tool to convert a MATLAB function block to 
  // fixed-point.The variant subsystem contains two blocks:
  // 1. MATLAB Function2 is the original code from the MATLAB function block. Modify this block to update your code 
  // or resolve errors
  // 
  // 2. MATLAB Function2_FixPt is the generated fixed-point code for the MATLAB function block. Any modifications to 
  // this block will be overwritten on the next conversion.
  // 
  // The Fixed-Point Tool will select an appropriate variant based on the Model Settings. Learn more. 


  zero_handle_FixPt u_zero_handle_FixPt (.u(u),  /* ufix16_En11 */
                                         .y(y)  /* ufix16_En11 */
                                         );

endmodule  // zero_handle

