# set_property IOSTANDARD LVCMOS33 [get_ports {data_in_out}]
# set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
# set_property SEVERITY {Warning} [get_drc_checks UCIO-1]

############################################################################

set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS True [current_design]

############################################################################
## FrontPanel Host Interface
############################################################################
set_property PACKAGE_PIN Y19 [get_ports {okHU[0]}]
set_property PACKAGE_PIN R18 [get_ports {okHU[1]}]
set_property PACKAGE_PIN R16 [get_ports {okHU[2]}]
set_property SLEW FAST [get_ports {okHU[*]}]
set_property IOSTANDARD LVCMOS18 [get_ports {okHU[*]}]

set_property PACKAGE_PIN W19 [get_ports {okUH[0]}]
set_property PACKAGE_PIN V18 [get_ports {okUH[1]}]
set_property PACKAGE_PIN U17 [get_ports {okUH[2]}]
set_property PACKAGE_PIN W17 [get_ports {okUH[3]}]
set_property PACKAGE_PIN T19 [get_ports {okUH[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {okUH[*]}]

set_property PACKAGE_PIN AB22 [get_ports {okUHU[0]}]
set_property PACKAGE_PIN AB21 [get_ports {okUHU[1]}]
set_property PACKAGE_PIN Y22 [get_ports {okUHU[2]}]
set_property PACKAGE_PIN AA21 [get_ports {okUHU[3]}]
set_property PACKAGE_PIN AA20 [get_ports {okUHU[4]}]
set_property PACKAGE_PIN W22 [get_ports {okUHU[5]}]
set_property PACKAGE_PIN W21 [get_ports {okUHU[6]}]
set_property PACKAGE_PIN T20 [get_ports {okUHU[7]}]
set_property PACKAGE_PIN R19 [get_ports {okUHU[8]}]
set_property PACKAGE_PIN P19 [get_ports {okUHU[9]}]
set_property PACKAGE_PIN U21 [get_ports {okUHU[10]}]
set_property PACKAGE_PIN T21 [get_ports {okUHU[11]}]
set_property PACKAGE_PIN R21 [get_ports {okUHU[12]}]
set_property PACKAGE_PIN P21 [get_ports {okUHU[13]}]
set_property PACKAGE_PIN R22 [get_ports {okUHU[14]}]
set_property PACKAGE_PIN P22 [get_ports {okUHU[15]}]
set_property PACKAGE_PIN R14 [get_ports {okUHU[16]}]
set_property PACKAGE_PIN W20 [get_ports {okUHU[17]}]
set_property PACKAGE_PIN Y21 [get_ports {okUHU[18]}]
set_property PACKAGE_PIN P17 [get_ports {okUHU[19]}]
set_property PACKAGE_PIN U20 [get_ports {okUHU[20]}]
set_property PACKAGE_PIN N17 [get_ports {okUHU[21]}]
set_property PACKAGE_PIN N14 [get_ports {okUHU[22]}]
set_property PACKAGE_PIN V20 [get_ports {okUHU[23]}]
set_property PACKAGE_PIN P16 [get_ports {okUHU[24]}]
set_property PACKAGE_PIN T18 [get_ports {okUHU[25]}]
set_property PACKAGE_PIN V19 [get_ports {okUHU[26]}]
set_property PACKAGE_PIN AB20 [get_ports {okUHU[27]}]
set_property PACKAGE_PIN P15 [get_ports {okUHU[28]}]
set_property PACKAGE_PIN V22 [get_ports {okUHU[29]}]
set_property PACKAGE_PIN U18 [get_ports {okUHU[30]}]
set_property PACKAGE_PIN AB18 [get_ports {okUHU[31]}]
set_property SLEW FAST [get_ports {okUHU[*]}]
set_property IOSTANDARD LVCMOS18 [get_ports {okUHU[*]}]

set_property PACKAGE_PIN N13 [get_ports {okAA}]
set_property IOSTANDARD LVCMOS18 [get_ports {okAA}]


create_clock -name okUH0 -period 9.920 [get_ports {okUH[0]}]

set_input_delay -add_delay -max -clock [get_clocks {okUH0}]  8.000 [get_ports {okUH[*]}]
set_input_delay -add_delay -min -clock [get_clocks {okUH0}] 10.000 [get_ports {okUH[*]}]
set_multicycle_path -setup -from [get_ports {okUH[*]}] 2

set_input_delay -add_delay -max -clock [get_clocks {okUH0}]  8.000 [get_ports {okUHU[*]}]
set_input_delay -add_delay -min -clock [get_clocks {okUH0}]  2.000 [get_ports {okUHU[*]}]
set_multicycle_path -setup -from [get_ports {okUHU[*]}] 2

set_output_delay -add_delay -max -clock [get_clocks {okUH0}]  2.000 [get_ports {okHU[*]}]
set_output_delay -add_delay -min -clock [get_clocks {okUH0}]  -0.500 [get_ports {okHU[*]}]

set_output_delay -add_delay -max -clock [get_clocks {okUH0}]  2.000 [get_ports {okUHU[*]}]
set_output_delay -add_delay -min -clock [get_clocks {okUH0}]  -0.500 [get_ports {okUHU[*]}]

# DACs #####################################################################
#set_property PACKAGE_PIN M9 [get_ports {DAC_out_pin[0][11]}]
#set_property PACKAGE_PIN L10 [get_ports {DAC_out_pin[0][10]}]
#set_property PACKAGE_PIN AB11 [get_ports {DAC_out_pin[0][8]}]
#set_property PACKAGE_PIN F15 [get_ports {DAC_out_pin[0][6]}]
#set_property PACKAGE_PIN F13 [get_ports {DAC_out_pin[0][4]}]
#set_property PACKAGE_PIN F14 [get_ports {DAC_out_pin[0][2]}]
#set_property PACKAGE_PIN AA15 [get_ports {DAC_out_pin[0][0]}]
set_property PACKAGE_PIN Y17 [get_ports {wr_ch0[0]}]
#set_property PACKAGE_PIN Y16 [get_ports {DAC_out_pin[0][9]}]
#set_property PACKAGE_PIN AA16 [get_ports {DAC_out_pin[0][7]}]
#set_property PACKAGE_PIN AB16 [get_ports {DAC_out_pin[0][5]}]
#set_property PACKAGE_PIN AB17 [get_ports {DAC_out_pin[0][3]}]
#set_property PACKAGE_PIN U7 [get_ports {DAC_out_pin[0][1]}]
set_property PACKAGE_PIN T3 [get_ports {wr_ch1[0]}]
set_property PACKAGE_PIN AB15 [get_ports {DAC_out_pin[0][11]}]
set_property PACKAGE_PIN W15 [get_ports {DAC_out_pin[0][10]}]
set_property PACKAGE_PIN W16 [get_ports {DAC_out_pin[0][8]}]
set_property PACKAGE_PIN Y13 [get_ports {DAC_out_pin[0][6]}]
set_property PACKAGE_PIN AA14 [get_ports {DAC_out_pin[0][4]}]
set_property PACKAGE_PIN AA13 [get_ports {DAC_out_pin[0][2]}]
set_property PACKAGE_PIN AB13 [get_ports {DAC_out_pin[0][0]}]
set_property PACKAGE_PIN Y8 [get_ports {wr_ch0[1]}]
set_property PACKAGE_PIN Y7 [get_ports {DAC_out_pin[0][9]}]
set_property PACKAGE_PIN R6 [get_ports {DAC_out_pin[0][7]}]
set_property PACKAGE_PIN T6 [get_ports {DAC_out_pin[0][5]}]
set_property PACKAGE_PIN W9 [get_ports {DAC_out_pin[0][3]}]
set_property PACKAGE_PIN Y9 [get_ports {DAC_out_pin[0][1]}]
set_property PACKAGE_PIN V9 [get_ports {wr_ch1[1]}]
set_property PACKAGE_PIN AB7 [get_ports {DAC_out_pin[1][11]}]
set_property PACKAGE_PIN AB6 [get_ports {DAC_out_pin[1][10]}]
set_property PACKAGE_PIN T5 [get_ports {DAC_out_pin[1][8]}]
set_property PACKAGE_PIN U5 [get_ports {DAC_out_pin[1][6]}]
set_property PACKAGE_PIN AA8 [get_ports {DAC_out_pin[1][4]}]
set_property PACKAGE_PIN AB8 [get_ports {DAC_out_pin[1][2]}]
set_property PACKAGE_PIN R4 [get_ports {DAC_out_pin[1][0]}]
set_property PACKAGE_PIN V8 [get_ports {wr_ch0[2]}]
set_property PACKAGE_PIN W6 [get_ports {DAC_out_pin[1][9]}]
set_property PACKAGE_PIN W5 [get_ports {DAC_out_pin[1][7]}]
set_property PACKAGE_PIN V7 [get_ports {DAC_out_pin[1][5]}]
set_property PACKAGE_PIN W7 [get_ports {DAC_out_pin[1][3]}]
set_property PACKAGE_PIN Y6 [get_ports {DAC_out_pin[1][1]}]
set_property PACKAGE_PIN AA6 [get_ports {wr_ch1[2]}]
set_property PACKAGE_PIN T4 [get_ports {DAC_out_pin[2][11]}]
set_property PACKAGE_PIN Y4 [get_ports {DAC_out_pin[2][10]}]
set_property PACKAGE_PIN AA4 [get_ports {DAC_out_pin[2][8]}]
set_property PACKAGE_PIN AB3 [get_ports {DAC_out_pin[2][6]}]
set_property PACKAGE_PIN AB2 [get_ports {DAC_out_pin[2][4]}]
set_property PACKAGE_PIN AA5 [get_ports {DAC_out_pin[2][2]}]
set_property PACKAGE_PIN AB5 [get_ports {DAC_out_pin[2][0]}]
set_property PACKAGE_PIN U6 [get_ports {wr_ch0[3]}]
set_property PACKAGE_PIN V5 [get_ports {DAC_out_pin[2][9]}]
set_property PACKAGE_PIN U3 [get_ports {DAC_out_pin[2][7]}]
set_property PACKAGE_PIN V3 [get_ports {DAC_out_pin[2][5]}]
set_property PACKAGE_PIN W2 [get_ports {DAC_out_pin[2][3]}]
set_property PACKAGE_PIN Y2 [get_ports {DAC_out_pin[2][1]}]
set_property PACKAGE_PIN T1 [get_ports {wr_ch1[3]}]
set_property PACKAGE_PIN J2 [get_ports {DAC_out_pin[3][11]}]
set_property PACKAGE_PIN D1 [get_ports {DAC_out_pin[3][10]}]
set_property PACKAGE_PIN E1 [get_ports {DAC_out_pin[3][8]}]
set_property PACKAGE_PIN A1 [get_ports {DAC_out_pin[3][6]}]
set_property PACKAGE_PIN B1 [get_ports {DAC_out_pin[3][4]}]
set_property PACKAGE_PIN H3 [get_ports {DAC_out_pin[3][2]}]
set_property PACKAGE_PIN K3 [get_ports {DAC_out_pin[3][0]}]
set_property PACKAGE_PIN K1 [get_ports {wr_ch0[4]}]
set_property PACKAGE_PIN G2 [get_ports {DAC_out_pin[3][9]}]
set_property PACKAGE_PIN H2 [get_ports {DAC_out_pin[3][7]}]
set_property PACKAGE_PIN B2 [get_ports {DAC_out_pin[3][5]}]
set_property PACKAGE_PIN C2 [get_ports {DAC_out_pin[3][3]}]
set_property PACKAGE_PIN G4 [get_ports {DAC_out_pin[3][1]}]
set_property PACKAGE_PIN H4 [get_ports {wr_ch1[4]}]
set_property PACKAGE_PIN L3 [get_ports {DAC_out_pin[4][11]}]
set_property PACKAGE_PIN D2 [get_ports {DAC_out_pin[4][10]}]
set_property PACKAGE_PIN E2 [get_ports {DAC_out_pin[4][8]}]
set_property PACKAGE_PIN J4 [get_ports {DAC_out_pin[4][6]}]
set_property PACKAGE_PIN K4 [get_ports {DAC_out_pin[4][4]}]
set_property PACKAGE_PIN H5 [get_ports {DAC_out_pin[4][2]}]
set_property PACKAGE_PIN J5 [get_ports {DAC_out_pin[4][0]}]
set_property PACKAGE_PIN E3 [get_ports {wr_ch0[5]}]
set_property PACKAGE_PIN F3 [get_ports {DAC_out_pin[4][9]}]
set_property PACKAGE_PIN M2 [get_ports {DAC_out_pin[4][7]}]
set_property PACKAGE_PIN M3 [get_ports {DAC_out_pin[4][5]}]
set_property PACKAGE_PIN J6 [get_ports {DAC_out_pin[4][3]}]
set_property PACKAGE_PIN K6 [get_ports {DAC_out_pin[4][1]}]
set_property PACKAGE_PIN L4 [get_ports {wr_ch1[5]}]
set_property PACKAGE_PIN M5 [get_ports {DAC_out_pin[5][11]}]
set_property PACKAGE_PIN M6 [get_ports {DAC_out_pin[5][10]}]
set_property PACKAGE_PIN F4 [get_ports {DAC_out_pin[5][8]}]
set_property PACKAGE_PIN P1 [get_ports {DAC_out_pin[5][6]}]
set_property PACKAGE_PIN R1 [get_ports {DAC_out_pin[5][4]}]
set_property PACKAGE_PIN N3 [get_ports {DAC_out_pin[5][2]}]
set_property PACKAGE_PIN N4 [get_ports {DAC_out_pin[5][0]}]
set_property PACKAGE_PIN L5 [get_ports {wr_ch0[6]}]
set_property PACKAGE_PIN L6 [get_ports {DAC_out_pin[5][9]}]
set_property PACKAGE_PIN N2 [get_ports {DAC_out_pin[5][7]}]
set_property PACKAGE_PIN P2 [get_ports {DAC_out_pin[5][5]}]
set_property PACKAGE_PIN P4 [get_ports {DAC_out_pin[5][3]}]
set_property PACKAGE_PIN P5 [get_ports {DAC_out_pin[5][1]}]
set_property PACKAGE_PIN N5 [get_ports {wr_ch1[6]}]
set_property PACKAGE_PIN Y12 [get_ports {DAC_out_pin[6][11]}]
set_property PACKAGE_PIN Y11 [get_ports {DAC_out_pin[6][10]}]
set_property PACKAGE_PIN Y14 [get_ports {DAC_out_pin[6][8]}]
set_property PACKAGE_PIN W14 [get_ports {DAC_out_pin[6][6]}]
set_property PACKAGE_PIN V14 [get_ports {DAC_out_pin[6][4]}]
set_property PACKAGE_PIN T15 [get_ports {DAC_out_pin[6][2]}]
set_property PACKAGE_PIN T14 [get_ports {DAC_out_pin[6][0]}]
set_property PACKAGE_PIN P6 [get_ports {wr_ch0[7]}]
set_property PACKAGE_PIN V15 [get_ports {DAC_out_pin[6][9]}]
set_property PACKAGE_PIN U15 [get_ports {DAC_out_pin[6][7]}]
set_property PACKAGE_PIN U16 [get_ports {DAC_out_pin[6][5]}]
set_property PACKAGE_PIN T16 [get_ports {DAC_out_pin[6][3]}]
set_property PACKAGE_PIN E17 [get_ports {DAC_out_pin[6][1]}]
set_property PACKAGE_PIN F16 [get_ports {wr_ch1[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {DAC_out_pin[*][*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wr_ch0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wr_ch1[*]}]

# ADCs #####################################################################
set_property PACKAGE_PIN Y1 [get_ports {cnv}]
set_property PACKAGE_PIN W1 [get_ports {ADC_output_enable}]
set_property PACKAGE_PIN AB1 [get_ports {data[1]}]
set_property PACKAGE_PIN AA1 [get_ports {data[3]}]
set_property PACKAGE_PIN AA3 [get_ports {data[5]}]
set_property PACKAGE_PIN Y3 [get_ports {data[7]}]
set_property PACKAGE_PIN W4 [get_ports {data[11]}]
set_property PACKAGE_PIN V4 [get_ports {data[12]}]
set_property PACKAGE_PIN V2 [get_ports {data[13]}]
set_property PACKAGE_PIN U2 [get_ports {data[14]}]
set_property PACKAGE_PIN U1 [get_ports {data[15]}]
set_property PACKAGE_PIN R2 [get_ports {data[0]}]
set_property PACKAGE_PIN R3 [get_ports {data[2]}]
set_property PACKAGE_PIN K2 [get_ports {ADC_clk_select}]
set_property PACKAGE_PIN L1 [get_ports {data[4]}]
set_property PACKAGE_PIN M1 [get_ports {data[6]}]
set_property PACKAGE_PIN G3 [get_ports {dco_in}]
set_property PACKAGE_PIN F1 [get_ports {data[8]}]
set_property PACKAGE_PIN G1 [get_ports {data[9]}]
set_property PACKAGE_PIN J1 [get_ports {data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_output_enable}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_clk_select}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[*] dco_in cnv}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets dco_in] 

# LEDs #####################################################################
# set_property PACKAGE_PIN A13 [get_ports {led[0]}]
# set_property PACKAGE_PIN B13 [get_ports {led[1]}]
# set_property PACKAGE_PIN A14 [get_ports {led[2]}]
# set_property IOSTANDARD LVCMOS15 [get_ports {led[*]}]



