`timescale 1ns / 1ps

module spgd_top #(
    parameter NUM_CHANNELS = 8,
    parameter ADC_WIDTH    = 16,
    parameter DAC_WIDTH    = 16
)(
    // System Clocks and Resets
    input  logic clk,
    input  logic rst_n,

    // Inputs from the processor
    input  logic        enable_loop,
    input  logic        manual_soft_reset,
    input  logic        auto_reset_enable,
    input  logic [15:0] auto_reset_period_ms,
    input  logic [11:0] v2pi_counts,
    input  logic [15:0] settle_cycles,
    input  logic [15:0] perturb_amp,
    input  logic [31:0] gamma_lr,
    input  logic [3:0]  epoch_bit_select,   // Hadamard epoch sign-flip control

    // Hardware Interfaces
    input  logic [ADC_WIDTH-1:0] adc_data_in,
    
    // Flattened array for Vivado IP Packager compatibility
    output logic [(NUM_CHANNELS*DAC_WIDTH)-1:0] dac_data_flat_out,

    // AXI-Stream Telemetry Logging Output (256-bit)
    output logic [255:0] m_axis_tdata,
    output logic         m_axis_tvalid,
    input  logic         m_axis_tready,
    output logic         m_axis_tlast
);

    // FSM to Datapath & Hadamard Dither
    logic advance_row;
    logic select_plus_minus;
    logic latch_j_plus;
    logic latch_j_minus;
    logic trigger_dsp_update;
    logic commit_new_u;

    // Hadamard Dither to Datapath
    logic [NUM_CHANNELS-1:0] dither_signs;

    // Unpacked DAC array from Datapath (easier to read)
    logic [DAC_WIDTH-1:0] dac_data_array [NUM_CHANNELS];
    
    // Internal flattened DAC data
    logic [(NUM_CHANNELS*DAC_WIDTH)-1:0] internal_dac_flat;

    // Flatten the output array for the IP block boundary
    genvar i;
    generate
        for (i = 0; i < NUM_CHANNELS; i++) begin : gen_flatten
            assign internal_dac_flat[(i*DAC_WIDTH) +: DAC_WIDTH] = dac_data_array[i];
        end
    endgenerate
    
    assign dac_data_flat_out = internal_dac_flat;

    // State Machine
    // auto_reset_pulse: one-clock pulse generated by FSM timer when enabled
    logic auto_reset_pulse;

    spgd_fsm u_fsm (
        .clk                (clk),
        .rst_n              (rst_n),
        .enable_loop        (enable_loop),
        .auto_reset_enable  (auto_reset_enable),
        .auto_reset_period_ms (auto_reset_period_ms),
        .auto_reset_pulse   (auto_reset_pulse),
        .settle_cycles      (settle_cycles),
        .advance_row        (advance_row),
        .select_plus_minus  (select_plus_minus),
        .latch_j_plus       (latch_j_plus),
        .latch_j_minus      (latch_j_minus),
        .trigger_dsp_update (trigger_dsp_update),
        .commit_new_u       (commit_new_u)
    );

    logic [2:0] current_row;
    logic [15:0] epoch_count;

    // Hadamard Dither Generator (replaces LFSR array)
    hadamard_dither #(
        .NUM_CHANNELS(NUM_CHANNELS)
    ) u_hadamard_dither (
        .clk             (clk),
        .rst_n           (rst_n),
        .advance_row     (advance_row),
        .epoch_bit_select(epoch_bit_select),
        .dither_signs    (dither_signs),
        .current_row     (current_row),
        .epoch_count     (epoch_count)
    );

    // Datapath outputs for telemetry
    logic signed [ADC_WIDTH:0] j_plus_out;
    logic signed [ADC_WIDTH:0] j_minus_out;
    logic signed [ADC_WIDTH:0] delta_j_out;
    logic signed [DAC_WIDTH-1:0] scaled_update_out;
    // Unperturbed baseline phases from datapath (what the algorithm converged to,
    // NOT the jittered DAC output which is u±du depending on FSM state)
    logic [(NUM_CHANNELS*DAC_WIDTH)-1:0] u_reg_flat;

    // Datapath
    spgd_datapath #(
        .NUM_CHANNELS(NUM_CHANNELS),
        .ADC_WIDTH(ADC_WIDTH),
        .DAC_WIDTH(DAC_WIDTH)
    ) u_datapath (
        .clk                (clk),
        .rst_n              (rst_n),
        .soft_reset         (manual_soft_reset | auto_reset_pulse),
        .select_plus_minus  (select_plus_minus),
        .latch_j_plus       (latch_j_plus),
        .latch_j_minus      (latch_j_minus),
        .trigger_dsp_update (trigger_dsp_update),
        .commit_new_u       (commit_new_u),
        .dither_signs       (dither_signs),
        .perturb_amp        (perturb_amp),
        .gamma_lr           (gamma_lr),
        .adc_data_in        (adc_data_in),
        .dac_data_out       (dac_data_array),
        .v2pi_counts        (v2pi_counts),
        .j_plus_out         (j_plus_out),
        .j_minus_out        (j_minus_out),
        .delta_j_out        (delta_j_out),
        .scaled_update_out  (scaled_update_out),
        .u_reg_flat_out     (u_reg_flat)
    );

    // ==========================================
    // AXI-Stream Telemetry Packing — Registered Handshake
    // ==========================================
    // tvalid is held high until tready is asserted (standard AXI-Stream handshake).
    // The guard condition `!m_axis_tvalid || m_axis_tready` ensures tdata is only
    // updated when the bus is idle OR a handshake is completing this cycle —
    // never while a beat is stalled waiting for tready (which would violate AXI-Stream).
    // New packets that arrive during backpressure are dropped (acceptable: the FIFO
    // downstream should almost never be full during normal operation).
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            m_axis_tvalid <= 1'b0;
            m_axis_tdata  <= '0;
        end else if (commit_new_u && (!m_axis_tvalid || m_axis_tready)) begin
            // Only latch when the stream is idle or the current beat is being accepted.
            // Packs the UNPERTURBED baseline u_reg, not the jittered DAC output.
            // Packet layout (256 bits = 8 x 32-bit AXI-Lite reads):
            //   [127:0]   u_reg_flat        8 x 16-bit unperturbed baseline phases
            //   [143:128] j_plus_out[15:0]  ADC reading at u+du (16-bit signed, fits in 16b)
            //   [159:144] j_minus_out[15:0] ADC reading at u-du (16-bit signed, fits in 16b)
            //   [175:160] delta_j[15:0]     Lower 16 bits of 17-bit gradient
            //   [191:176] scaled_update      gamma*dj>>16, DAC_WIDTH bits sign-extended to 16
            //   [207:192] epoch_count        Hadamard epoch counter
            //   [215:208] {5'd0, row[2:0]}  Current Hadamard row index
            //   [216]     delta_j[16]       MSB of 17-bit delta_j (overflow guard bit)
            //             Needed because delta_j = j+ - j- can reach ±65535 which requires
            //             17 bits; without this bit +40000 aliases to -25536 in Python.
            //   [255:217] 39'd0             Reserved
            m_axis_tdata[127:0]   <= u_reg_flat;
            m_axis_tdata[143:128] <= j_plus_out[15:0];
            m_axis_tdata[159:144] <= j_minus_out[15:0];
            m_axis_tdata[175:160] <= delta_j_out[15:0];   // lower 16 bits
            m_axis_tdata[191:176] <= {{(16-DAC_WIDTH){scaled_update_out[DAC_WIDTH-1]}}, scaled_update_out};
            m_axis_tdata[207:192] <= epoch_count;
            m_axis_tdata[215:208] <= {5'd0, current_row};
            m_axis_tdata[216]     <= delta_j_out[16];     // MSB — prevents aliasing for |dj|>32767
            m_axis_tdata[255:217] <= 39'd0;               // Reserved
            m_axis_tvalid         <= 1'b1;
        end else if (m_axis_tready && m_axis_tvalid) begin
            // Clear valid once the FIFO has accepted the beat
            m_axis_tvalid <= 1'b0;
        end
    end

    assign m_axis_tlast = 1'b0; // Not using packet frame boundaries

endmodule