`timescale 1ns / 1ps

module spgd_top #(
    parameter NUM_CHANNELS = 8,
    parameter ADC_WIDTH    = 16,
    parameter DAC_WIDTH    = 16
)(
    // System Clocks and Resets
    input  logic clk,
    input  logic rst_n,

    // Inputs from the processor
    input  logic        enable_loop,
    input  logic        manual_soft_reset,
    input  logic        auto_reset_enable,
    input  logic [15:0] auto_reset_period_ms,
    input  logic [11:0] v2pi_counts,
    input  logic [15:0] settle_cycles,
    input  logic [15:0] perturb_amp,
    input  logic [31:0] gamma_lr,
    input  logic [3:0]  epoch_bit_select,   // Hadamard epoch sign-flip control

    // Hardware Interfaces
    input  logic [ADC_WIDTH-1:0] adc_data_in,
    
    // Flattened array for Vivado IP Packager compatibility
    output logic [(NUM_CHANNELS*DAC_WIDTH)-1:0] dac_data_flat_out
);

    // FSM to Datapath & Hadamard Dither
    logic advance_row;
    logic select_plus_minus;
    logic latch_j_plus;
    logic latch_j_minus;
    logic trigger_dsp_update;
    logic commit_new_u;

    // Hadamard Dither to Datapath
    logic [NUM_CHANNELS-1:0] dither_signs;

    // Unpacked DAC array from Datapath (easier to read)
    logic [DAC_WIDTH-1:0] dac_data_array [NUM_CHANNELS];

    // Flatten the output array for the IP block boundary
    genvar i;
    generate
        for (i = 0; i < NUM_CHANNELS; i++) begin : gen_flatten
            assign dac_data_flat_out[(i*DAC_WIDTH) +: DAC_WIDTH] = dac_data_array[i];
        end
    endgenerate

    // State Machine
    // auto_reset_pulse: one-clock pulse generated by FSM timer when enabled
    logic auto_reset_pulse;

    spgd_fsm u_fsm (
        .clk                (clk),
        .rst_n              (rst_n),
        .enable_loop        (enable_loop),
        .auto_reset_enable  (auto_reset_enable),
        .auto_reset_period_ms (auto_reset_period_ms),
        .auto_reset_pulse   (auto_reset_pulse),
        .settle_cycles      (settle_cycles),
        .advance_row        (advance_row),
        .select_plus_minus  (select_plus_minus),
        .latch_j_plus       (latch_j_plus),
        .latch_j_minus      (latch_j_minus),
        .trigger_dsp_update (trigger_dsp_update),
        .commit_new_u       (commit_new_u)
    );

    // Hadamard Dither Generator (replaces LFSR array)
    hadamard_dither #(
        .NUM_CHANNELS(NUM_CHANNELS)
    ) u_hadamard_dither (
        .clk             (clk),
        .rst_n           (rst_n),
        .advance_row     (advance_row),
        .epoch_bit_select(epoch_bit_select),
        .dither_signs    (dither_signs),
        .current_row     (),             // Diagnostic — unconnected for now
        .epoch_count     ()              // Diagnostic — unconnected for now
    );

    // Datapath
    spgd_datapath #(
        .NUM_CHANNELS(NUM_CHANNELS),
        .ADC_WIDTH(ADC_WIDTH),
        .DAC_WIDTH(DAC_WIDTH)
    ) u_datapath (
        .clk                (clk),
        .rst_n              (rst_n),
        .soft_reset         (manual_soft_reset | auto_reset_pulse),
        .select_plus_minus  (select_plus_minus),
        .latch_j_plus       (latch_j_plus),
        .latch_j_minus      (latch_j_minus),
        .trigger_dsp_update (trigger_dsp_update),
        .commit_new_u       (commit_new_u),
        .dither_signs       (dither_signs),
        .perturb_amp        (perturb_amp),
        .gamma_lr           (gamma_lr),
        .adc_data_in        (adc_data_in),
        .dac_data_out       (dac_data_array),
        .v2pi_counts        (v2pi_counts)
    );

endmodule